apiVersion: v1
kind: Service
metadata:
  name: PropAi Sync
  labels:
    app: PropAi Sync
spec:
  type: ClusterIP
  selector:
    app: PropAi Sync
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP

